<a href="https://colab.research.google.com/github/inderpreetsingh01/ml_machine_coding/blob/main/convolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def conv2d(X, K, stride=1):
    """
    X: input 2D array (H, W)
    K: kernel 2D array (kH, kW)
    stride: stride of convolution
    Returns: convolved output
    """
    H, W = X.shape
    kH, kW = K.shape

    out_h = (H - kH) // stride + 1
    out_w = (W - kW) // stride + 1

    output = np.zeros((out_h, out_w))

    for i in range(0, out_h):
        for j in range(0, out_w):
            patch = X[i*stride:i*stride+kH, j*stride:j*stride+kW]
            output[i, j] = np.sum(patch * K)
    return output

In [2]:
X = np.array([
    [1, 2, 3, 0],
    [0, 1, 2, 3],
    [3, 0, 1, 2],
    [2, 3, 0, 1]
])

K = np.array([
    [1, 0],
    [0, -1]
])

output = conv2d(X, K, stride=1)
print(output)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
