<a href="https://colab.research.google.com/github/inderpreetsingh01/ml_machine_coding/blob/main/normalisation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def min_max_normalize(X):
    X_min = X.min(axis=0)
    X_max = X.max(axis=0)
    return (X - X_min) / (X_max - X_min + 1e-10)  # small epsilon to avoid division by zero


In [2]:
X = np.array([[1, 2], [3, 4], [5, 6]])
print(min_max_normalize(X))


[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


In [3]:
def z_score_normalize(X):
    mean = X.mean(axis=0)
    std = X.std(axis=0)
    return (X - mean) / (std + 1e-10)


In [4]:
X = np.array([[1, 2], [3, 4], [5, 6]])
print(z_score_normalize(X))


[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [5]:
def batch_normalize(X, gamma=None, beta=None, eps=1e-5):
    mean = X.mean(axis=0)
    var = X.var(axis=0)
    X_hat = (X - mean) / np.sqrt(var + eps)

    if gamma is not None:
        X_hat = X_hat * gamma
    if beta is not None:
        X_hat = X_hat + beta
    return X_hat


In [6]:
X = np.random.rand(4,3)
gamma = np.ones(3)
beta = np.zeros(3)
print(batch_normalize(X, gamma, beta))


[[ 1.46063185 -1.67066863 -0.32522493]
 [-0.729836    0.1296261   1.34420721]
 [-1.09549488  0.72520346  0.37527644]
 [ 0.36469903  0.81583908 -1.39425872]]


In [7]:
def layer_normalize(X, eps=1e-5):
    mean = X.mean(axis=1, keepdims=True)
    var = X.var(axis=1, keepdims=True)
    return (X - mean) / np.sqrt(var + eps)
